# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTKBcxDVimTrtdQltLBizJmJnx5kcQQJ
"""

print("helo,excited to start data science.")

customer_name = "John Doe"
customer_age = 28
customer_balance = 120.75
print("Customer:", customer_name)
print("Age:", customer_age)
print("Balance:", customer_balance)

product_price = 200
discount = product_price * 0.10 # 10% discount
final_price = product_price - discount
print("Final Price after Discount:", final_price)

import numpy as np
sales=np.array([150,200,250,300,400,350,500])
print("sales data:",sales)

print("average sales:",np.mean(sales))
print("highest sales:",np.max(sales))
print("lowest sales:",np.min(sales))

import pandas as pd
data = {
"Customer": ["Alice", "Bob", "Charlie"],
"Age": [25, 30, 35],
"Amount Spent": [120, 200, 150]
}
df = pd.DataFrame(data)
print(df)

from google.colab import files
uploaded=files.upload() # Upload your CSV file
df = pd.read_csv("Siva.txt") # Replace with your file name
df.head()

df.to_csv("cleaned_customer_data.csv", index=False)
files.download("cleaned_customer_data.csv") # Download the file

import pandas as pd
data = {
"Customer": ["Alice", "Bob", "Charlie","Siva","Arul","Sanjay","preethi"],
"Age": [25, 30, 35,19,20,24,18],
"Amount Spent": [120, 200, 150,250,300,100,50]
}
df = pd.DataFrame(data)
print(df)
high_spenders = df[df["Amount Spent"] > 150]
print(high_spenders)

import pandas as pd
data = {
"Customer": ["Alice", "Bob", "Charlie","Siva","Arul","Sanjay","preethi"],
"Age": [25, 30, 35,19,20,24,18],
"Amount Spent": [120, 200, 150,250,300,100,50]
}
df = pd.DataFrame(data)
print(df)
df_sorted = df.sort_values(by="Amount Spent", ascending=False)
print(df_sorted)

import pandas as pd
data = {
"Customer": ["Alice", "Bob", "Charlie","Siva","Arul","Sanjay","preethi"],
"Age": [25, 30, 35,19,20,24,18],
"Amount Spent": [120, 200, 150,250,300,100,50]
}
df = pd.DataFrame(data)
print(df)
df["Loyalty Points"] = df["Amount Spent"] // 10
print(df)

from google.colab import files
uploaded=files.upload() # Upload your CSV file
df = pd.read_csv("Siva.txt") # Replace with your file name
df.head()
df.to_csv("cleaned_Siva.txt", index=False)
files.download("cleaned_Siva.txt") # Download the file