# -*- coding: utf-8 -*-
"""Ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AN-GU_irOGiQfzwkKNu47Asilpk0L8cG
"""

patient_name="muthu kumar"
patient_age=35
patient_weight_kg=75
patient_height_m=1.75
patient_bmi=patient_weight_kg/(patient_height_m**2)
print(f"patient name:{patient_name}")
print(f"age:{patient_age}years")
print(f"BMI:{patient_bmi:.2f}")