# -*- coding: utf-8 -*-
"""Ex4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uq-auNBh5WZoeG84OeoATmIfcEPlJSWB
"""

import pandas as pd

# Creating the DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [45, 50, 38, 60, 55],
    "Cholesterol": [200, 220, 180, 250, 230]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

import pandas as pd

# Sample patient data
data = {
    'Patient_ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Cholesterol': [180, 220, 190, 250, 210]
}

# Create DataFrame
df = pd.DataFrame(data)

# Set cholesterol threshold
threshold = 200

# Filter patients above the threshold
high_cholesterol_patients = df[df['Cholesterol'] > threshold]

# Display results
print(high_cholesterol_patients)